# netlify.toml

[[plugins]]
package = "."
  [plugins.inputs]
    excludeFiles = ["/exclude/**"] # default = []
    applyContainer = ".rte-content" # default = "body"
    excludeElements = '[data-src], .lazy-load' # default = '[data-src], .lazy-load'
    replaceThreshold = 0 # default = 0
